spring:
  application:
    name: fixlog

  # Google OAuth2 Client 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: { client id }
            client-secret: { client key }
            scope:
              - profile
              - email

  # PostgreSQL 17 설정
  datasource:
    url: jdbc:postgresql://192.168.56.102:5432/apj_db
    username: kth
    password: taehokwon48
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /fixlog
